### PR TITLE
feat: declarative instrumentation

### PR DESCRIPTION
**Pull request by davidnuescheler**
https://declarative-instrumentation--business-website--adobe.hlx3.page/blog/insights/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy

### CODE REVIEW

**Comment by kptdobe** [comment]
Couldn't we create a `post-martech.js` script that is called as callback of `loadMartech` ? The `setDigitalData` will grow (check https://github.com/adobe/spark-website/blob/main/express/scripts/instrument.js#L50-L381, 330 lines of `digitalData._set(...)`) which will slowly increase the size of `script.js`.

**Comment by bbythewa** [comment]
Hey @kptdobe,

The helix ccx implementation (spark website) was kind of a strange case.  There were reasons for why it bloated that I don't think business website suffers from. A few I can think of off the top of my head:

1. There were really 2 separate implementations that we had to merge together into one (the adobe.com specification and the spark specification)
2. The spark specification had a lot of custom dimension requirements simply to keep parity with their previous implementation. 
3. There were a lot of features, capabilities, widgets, CTAs, etc. in the CCX helix pages that required a more complex set of rules for setting data in the data layer.
4. Finally, there wasn't a lot of time to design and there wasn't a focus on code optimization/minimization at the time and it was more important to get it out the door than design it well...

In the case of business blogs, most of these things do not exist.  Hopefully that at least gives some context and history behind the reasons for bloat in digitalData.  I like David's approach because it tries to avoid inserting that directly in the code and thus avoiding the bloat.

**Comment by bbythewa** [comment]
@davidnuescheler, first I have to say that I really love this idea.  This is a really great implementation and I approve of the concept.  Thanks for putting it together.

**A couple of concerns:**
1. If we do this, it delays the loading of main.min.js, which also delays the hiding/unhiding of the body (FCP, LCP, SPI all are affected by the body hiding).  This is probably my biggest concern.
2. (minor) When we want to expand this to things other than `<meta>` tags, we will have to modify the implementation a bit.  Are we certain all the data we will want will be in meta tags?
3. (minor) I didn't see any implementations of the event tracking tab, but my concern mainly revolves around this json file being loaded on EVERY page, but only on some pages will the links be relevant.  This incurs the network cost on every page where it may not be used or needed. 

**Possible solutions:**
1. Is there any way to embed the content of instrument.json in the HTML content itself to avoid the extra network time?  Do you have any precedent or patterns for this sort of thing?
2. A page specific json file? (instrument.blog.json, instrument.improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy.json, etc.)

**Comment by davidnuescheler** [comment]
@bbythewa i changed the implementation which should address (1), as we are no longer waiting. there is some tracking in there to see how "unlikely" the loss of information is, see the `unknown:` categories...  

as for (2), you are absolutely correct, once we get other usecases for things that need to go into digital data we should probably extend the sheet. i think the implementation is somewhat obvious as we probably would use a query selector (+ possibly some additional selection of attributes and transformations) but i would like to learn what those usecases are and keep it simple for now.

for (3), i think there are two concerns 
(a) that there is an overhead with loading the `instrumentation.json` at all, and 
(b) that there may be extra information about certain mappings that are not needed for this particular page in there. 

first let me state that i think the overhead of (a) and (b) is negligible considering that we are outside of the critical path and i don't think that the payload should ever get bigger than a couple of kb (it is 405b with our admittedly very simple configuration). 
the benefit of keeping this as separate resource that can be cached by the browser (vs. being inlined), should also have a positive overall network impact, and simplify things for the entire caching chain (CDN, proxies, etc.) and as for (b) i think in pure JS implementation the entire set of instrumentation logic is also transmitted, and at least from a network footprint, the JSON mapping should be smaller.

let me know what you think...

**Comment by bbythewa** [comment]
@davidnuescheler, I like the changes you have made and also agree with your assessment.  I approve.

**Review by bbythewa — APPROVED** [review]

**Pull request merged**
