### PR TITLE
Adding eventListener for custom event from gnav.init() and match the …

### PR DESCRIPTION
**Pull request by seanchoi-workfront**
…cta href if it is existed.

Jira ticket: [MWPW-106285](https://jira.corp.adobe.com/browse/MWPW-106285)
Testing URL:
Main: https://main--business-website--adobe.hlx3.page/drafts/cmillar/gnav/
This change: https://gnav-banner-match--business-website--adobe.hlx3.page/drafts/cmillar/gnav/

You should see the footer banner CTA's URL is matching with Gnav's one.

Screen Shot 2022-03-30 at 5 38 29 PM

I also created a PR for `adobecom/gnav`: https://github.com/adobecom/gnav/pull/9.

### CODE REVIEW

**Comment by seanchoi-workfront** [comment]
> Fix the linting errors (either use the console abstraction or use an eslint-diable), otherwise 👍 .

That console log is from [scripts/delayed.js](https://github.com/adobe/business-website/pull/202/files#diff-2c92a267a7d73a4c0a3dd9d6d960e4fbbf07254a75154691fc24fc9beb4f9d43) which isn't even part of this PR. Do you still want me to touch it with this PR?

**Comment by auniverseaway** [comment]
@seanchoi-workfront Yeah. At least throw the eslint-disable in.

**Review by chrischrischris — COMMENTED** [review]
Looks good.

I think it would be better to emit the event inside of Gnav.init instead of in the blockEl init.  Thoughts?

Super minor nit - prefer `:` to `.` to separate item:eventName: `gnav:init` or if we really want to namespace it for helix: `helix:gnav.init`

**Comment by seanchoi-workfront** [comment]
> @seanchoi-workfront Yeah. At least throw the eslint-disable in.

done!

**Comment by seanchoi-workfront** [comment]
> Looks good.
> 
> I think it would be better to emit the event inside of Gnav.init instead of in the blockEl init. Thoughts?
> 
> Super minor nit - prefer `:` to `.` to separate item:eventName: `gnav:init` or if we really want to namespace it for helix: `helix:gnav.init`

I changed it `gnav:init`.
I thought about having event inside gnav.init() but then I realized it would be much more safer to attach to the element that gnav will be on. Chris also mentioned this:

image

**Comment by chrischrischris** [comment]
no need to change - you do have access to the block el via `this.el` but really doesn't matter

**Pull request merged**
